pipeline:
  name: harness-ci-cd
  identifier: harnesscicd
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: githubcloudpersonal
        repoName: harness-ci-cd
        build:
          spec:
            branch: feature/csdaai-600-gce-using-harness-cicd
          type: branch
  stages:
    - stage:
        name: initial
        identifier: initial
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: echo
                  identifier: echo
                  spec:
                    shell: Sh
                    command: echo "Hello World"
    - stage:
        name: tfplan
        identifier: tfplan
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: TerraformCloudRun
                  name: TerraformCloudRun_1
                  identifier: TerraformCloudRun_1
                  spec:
                    runType: Plan
                    runMessage: ran from Harness
                    spec:
                      organization: lbg-cloud-platform
                      workspace: ws-Jyh6kwTq3HCCXZ37
                      variables: []
                      discardPendingRuns: true
                      targets: []
                      connectorRef: tfcloudpersonalaccount
                      provisionerIdentifier: testdelegateprovisioner
                      planType: Apply
                    delegateSelectors:
                      - helm-delegate
                  timeout: 10m
              - step:
                  type: TerraformPlan
                  name: TerraformPlan_1
                  identifier: TerraformPlan_1
                  spec:
                    provisionerIdentifier: testdelegateprovisioner
                    configuration:
                      command: Apply
                      configFiles:
                        store:
                          spec:
                            connectorRef: delegategitpersonal
                            repoName: harness-ci-cd
                            gitFetchType: Branch
                            branch: feature/csdaai-600-gce-using-harness-cicd
                            folderPath: ./
                          type: Github
                      secretManagerRef: org.harnessSecretManager
                    delegateSelectors:
                      - helm-delegate
                  timeout: 10m
        tags: {}
        delegateSelectors:
          - helm-delegate
    - stage:
        name: buildtfplan
        identifier: buildtfplan
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: terraform plan
