pipeline:
  name: harness-ci-cd
  identifier: harnesscicd
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: githubcloudpersonal
        repoName: harness-ci-cd
        build:
          spec:
            branch: feature/csdaai-600-gce-using-harness-cicd
          type: branch
  stages:
    - stage:
        name: initial
        identifier: initial
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: echo
                  identifier: echo
                  spec:
                    shell: Sh
                    command: echo "Hello World"
