pipeline:
  name: harness-ci-cd
  identifier: harnesscicd
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: tfplan
        identifier: tfplan
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: TerraformCloudRun
                  name: TerraformCloudRun_1
                  identifier: TerraformCloudRun_1
                  spec:
                    runType: Plan
                    runMessage: ran from Harness
                    spec:
                      organization: lbg-cloud-platform
                      workspace: ws-Jyh6kwTq3HCCXZ37
                      variables: []
                      discardPendingRuns: true
                      targets: []
                      connectorRef: tfcloudpersonalaccount
                      provisionerIdentifier: testdelegateprovisioner
                      planType: Apply
                    delegateSelectors:
                      - helm-delegate
                  timeout: 10m
              - step:
                  type: TerraformCloudRun
                  name: TerraformCloudRun_2
                  identifier: TerraformCloudRun_2
                  spec:
                    runType: Apply
                    spec:
                      provisionerIdentifier: testdelegateprovisioner
                  timeout: 2h
        tags: {}
        delegateSelectors:
          - helm-delegate
